#!/usr/bin/env bash
if [[ $1 == hed ]]
then
  printf "\e[1;32mConnecting to Gionee Headphones\n\e[0m"
  id=FC:58:FA:44:84:CA
elif [[ $1 == ear ]]
then
  printf "\e[1;32mConnecting to UiNB Earphones\n\e[0m"
  id=BD:1E:5E:40:70:CE
elif [[ $1 == air ]]
then
  printf "\e[1;32mConnecting to Airpods pro 2\n\e[0m"
  id=44:C0:03:C3:36:0C
elif [[ $1 == speak ]]
then
  printf "\e[1;32mConnecting to Speaker(Bluetooth Reciever)\n\e[0m"
  id=5D:19:C0:38:C1:A4
elif [[ $1 == help ]]
then
  printf "\e[1;32m(This program uses bluetoothctl)\nhed --> Gionee Headphones\near --> UiNB Earphones\nspeak --> Speaker(Bluetooth Reciever)\ndisc --> Disconnect\nlist --> List Nearby Devices\n\e[0m"
  exit
elif [[ $1 == disc ]]
then
  bluetoothctl power on & disown ; bluetoothctl disconnect
  exit
elif [[ $1 == list ]]
then
  bluetoothctl power on & disown ; bluetoothctl devices
  exit
elif [[ $1 == f ]]
then
  bluetoothctl disconnect && sleep 0.5 && bluetoothctl connect 44:C0:03:C3:36:0C && sleep 5 && dunstctl close && dunstctl close
  exit
elif [[ $1 == o ]]
then
  bluetoothctl power off
  exit
else
    echo Invalid argument
    exit
fi
bluetoothctl power on & disown
sleep 0.5
bluetoothctl scan on & disown
bluetoothctl disconnect & disown
bluetoothctl connect $id
