#!/usr/bin/env bash

current_dir="."

while true; do
    selection=$( (ls -a -N --color=always --group-directories-first "$current_dir" ; echo -e "\e[1;33mSEARCH-ALL\e[0m") | \
        fzf --ansi --preview "\
        if [ -f '""$current_dir"/{}"' ]; then
            bat --theme="Dracula" --color=always --decorations=never '$current_dir'/{};
        else
            ls -a -N --color=always --group-directories-first '$current_dir'/{};
            fi" \
        --layout=reverse \
        --bind="left:pos(2)+accept,right:accept,ctrl-d:execute-silent(mv {} ~/Trash),ctrl-alt-d:execute(sudo mv {} ~/Trash)"\
        --query "'")

            if [ "$selection" == "." ]; then
                cd "$current_dir"
                break
            fi

            if [ "$selection" == "" ]; then
                echo $current_dir
                echo $selected_path
                break
            fi

            selected_path="$current_dir/$selection"

            if [ "$selection" == "SEARCH-ALL" ]; then
                selected_path=$(find "$current_dir" -print | 
                    while IFS= read -r item; do 
                        if [ -d "$item" ]; then
                            echo -e "\e[1;34m$item\e[0m"
                        elif [ -x "$item" ]; then
                            echo -e "\e[1;32m$item\e[0m"
                        else
                            echo "$item"
                        fi
                    done | 
                        fzf --ansi --preview "\
                        if [ -f \'{}\' ]; then
                            bat --theme=Dracula --color=always --decorations=never {};
                        else
                            ls -a -N --color=always --group-directories-first {};
                            fi" \
                                --layout=reverse \
                                --query "'")
            fi

            if [ -d "$selected_path" ]; then
                current_dir="$selected_path"
            else
                # xdg-open "$selected_path"&>/dev/null&
                nvim "$selected_path"
                disown
            fi

            clear
        done
